/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health status. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skill/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skill descriptor version */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current skill.md version. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SkillVersion"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Signup payload. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignupInput"];
                };
            };
            responses: {
                /** @description Created account and one-time keys. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignupResponse"];
                    };
                };
                /** @description Bad request or provider credential error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Missing, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Authenticated key lacks required scope. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Requested resource or provider connection not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Quota or rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account/api-keys/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate current API key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New API key. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RotateApiKeyResponse"];
                    };
                };
                /** @description Bad request or provider credential error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Missing, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Authenticated key lacks required scope. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Requested resource or provider connection not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Quota or rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get authenticated account */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Authenticated account. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                /** @description Bad request or provider credential error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Missing, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Authenticated key lacks required scope. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Requested resource or provider connection not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Quota or rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get account usage */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usage summary. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountUsage"];
                    };
                };
                /** @description Bad request or provider credential error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Missing, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Authenticated key lacks required scope. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Requested resource or provider connection not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Quota or rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List provider connections */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active provider connections. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Connection"][];
                    };
                };
                /** @description Bad request or provider credential error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Missing, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Authenticated key lacks required scope. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Requested resource or provider connection not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Quota or rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /** Connect provider */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Provider connection payload. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateConnectionInput"];
                };
            };
            responses: {
                /** @description Created connection. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Connection"];
                    };
                };
                /** @description Bad request or provider credential error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Missing, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Authenticated key lacks required scope. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Requested resource or provider connection not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Quota or rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete provider connection */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: components["schemas"]["Provider"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted connection. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteConnectionResponse"];
                    };
                };
                /** @description Bad request or provider credential error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Missing, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Authenticated key lacks required scope. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Requested resource or provider connection not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Quota or rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools/upsert_contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or update contact */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Contact upsert payload. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertContactInput"];
                };
            };
            responses: {
                /** @description Contact upsert result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpsertContactResponse"];
                    };
                };
                /** @description Bad request or provider credential error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Missing, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Authenticated key lacks required scope. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Requested resource or provider connection not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Quota or rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools/get_connection_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get provider connection status */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Connection status payload. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GetConnectionStatusInput"];
                };
            };
            responses: {
                /** @description Connection status result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetConnectionStatusResponse"];
                    };
                };
                /** @description Bad request or provider credential error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Missing, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Authenticated key lacks required scope. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Requested resource or provider connection not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Quota or rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools/send_transactional": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send transactional email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Transactional email payload. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendTransactionalInput"];
                };
            };
            responses: {
                /** @description Transactional send result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SendTransactionalResponse"];
                    };
                };
                /** @description Bad request or provider credential error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Missing, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Authenticated key lacks required scope. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Requested resource or provider connection not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Quota or rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Tool/provider pair is not supported. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools/get_campaign_stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get campaign stats */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Campaign stats payload. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GetCampaignStatsInput"];
                };
            };
            responses: {
                /** @description Campaign stats result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetCampaignStatsResponse"];
                    };
                };
                /** @description Bad request or provider credential error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Missing, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Authenticated key lacks required scope. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Requested resource or provider connection not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Quota or rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Tool/provider pair is not supported. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools/list_templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List provider templates */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Template list payload. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ListTemplatesInput"];
                };
            };
            responses: {
                /** @description Template list result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListTemplatesResponse"];
                    };
                };
                /** @description Bad request or provider credential error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Missing, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Authenticated key lacks required scope. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Requested resource or provider connection not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Quota or rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Tool/provider pair is not supported. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools/list_campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List provider campaigns */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Campaign list payload. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ListCampaignsInput"];
                };
            };
            responses: {
                /** @description Campaign list result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListCampaignsResponse"];
                    };
                };
                /** @description Bad request or provider credential error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Missing, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Authenticated key lacks required scope. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Requested resource or provider connection not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Quota or rate limit exceeded. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Tool/provider pair is not supported. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Plan-period quota state.
         * @example {
         *       "used": 42,
         *       "limit": 1000,
         *       "resets_at": "2026-05-01T00:00:00.000Z"
         *     }
         */
        QuotaMeta: {
            /** @example 42 */
            used: number;
            /** @example 1000 */
            limit: number;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp.
             * @example 2026-04-27T12:00:00.000Z
             */
            resets_at: string;
            /** @example false */
            check_skipped?: boolean;
        };
        /** @description Success envelope metadata. */
        SuccessMeta: {
            /** @example 01HV0000000000000000000000 */
            request_id: string;
            /** @example 2 */
            queue_time_ms: number;
            /** @example 234 */
            execution_time_ms: number;
            /** @example 236 */
            total_latency_ms: number;
            quota: components["schemas"]["QuotaMeta"];
            ratelimit?: {
                /** @example false */
                check_skipped?: boolean;
            };
            idempotency?: {
                replay: boolean;
            };
            provider_metadata?: {
                [key: string]: unknown;
            };
            job?: {
                /** @enum {string} */
                status: "pending";
                /** @example job_abc123 */
                job_id: string;
                /** @example Check the provider job before replaying. */
                hint: string;
            };
            /** @example true */
            _test_mode?: boolean;
        };
        /**
         * @description Stable server-side error category.
         * @example user_input
         * @enum {string}
         */
        ErrorCategory: "user_input" | "provider_fault" | "transient" | "system";
        /**
         * @description Supported provider identifier.
         * @example sendgrid
         * @enum {string}
         */
        Provider: "sendgrid" | "mailchimp" | "klaviyo";
        /**
         * @description Canonical Vorlek error envelope.
         * @example {
         *       "status": "error",
         *       "error": {
         *         "code": "INVALID_PARAMS",
         *         "message": "Request validation failed.",
         *         "category": "user_input",
         *         "retry_safe": false
         *       },
         *       "meta": {
         *         "request_id": "01HV0000000000000000000000"
         *       }
         *     }
         */
        ErrorEnvelope: {
            /** @enum {string} */
            status: "error";
            error: {
                /** @example INVALID_PARAMS */
                code: string;
                /** @example Request validation failed. */
                message: string;
                category: components["schemas"]["ErrorCategory"];
                /** @example false */
                retry_safe: boolean;
                provider?: components["schemas"]["Provider"];
                fix?: {
                    /** @example fix_request_body */
                    action: string;
                    /** @example Check the field-level validation detail. */
                    hint: string;
                };
                detail?: unknown;
            };
            meta: {
                /** @example 01HV0000000000000000000000 */
                request_id: string;
                /** @example 87 */
                total_latency_ms?: number;
                quota?: components["schemas"]["QuotaMeta"];
            };
        };
        /**
         * @description Create or update one contact at a connected provider.
         * @example {
         *       "provider": "sendgrid",
         *       "email": "jamie@example.com",
         *       "first_name": "Jamie",
         *       "properties": {
         *         "plan": "free"
         *       }
         *     }
         */
        UpsertContactInput: {
            /** @enum {string} */
            provider: "sendgrid" | "mailchimp" | "klaviyo";
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            phone?: string;
            properties?: {
                [key: string]: string | number | boolean;
            };
        };
        /** @description Normalized upsert_contact result. */
        UpsertContactData: {
            /** @example f1ec8680-0000-4000-8000-000000000000 */
            contact_id: string;
            /**
             * @example upserted
             * @enum {string}
             */
            action: "created" | "updated" | "upserted";
            /**
             * @example [
             *       "plan"
             *     ]
             */
            fields_auto_created: string[];
            provider: components["schemas"]["Provider"];
        };
        /**
         * @description Check whether a connected provider credential is active.
         * @example {
         *       "provider": "sendgrid"
         *     }
         */
        GetConnectionStatusInput: {
            /** @enum {string} */
            provider: "sendgrid" | "mailchimp" | "klaviyo";
        };
        /** @description Normalized provider connection status. */
        ConnectionStatusData: {
            provider: components["schemas"]["Provider"];
            /**
             * @example active
             * @enum {string}
             */
            status: "active" | "invalid" | "unreachable";
            /**
             * Format: date-time
             * @description ISO 8601 timestamp.
             * @example 2026-04-27T12:00:00.000Z
             */
            last_validated_at: string;
            /**
             * @example {
             *       "account_name": "Dogfood Workspace"
             *     }
             */
            account_info: {
                [key: string]: string | number | boolean | null;
            } | null;
        };
        /**
         * @description Send one transactional email through a supported provider.
         * @example {
         *       "provider": "sendgrid",
         *       "to": "recipient@example.com",
         *       "subject": "Hello",
         *       "text": "Hello from Vorlek"
         *     }
         */
        SendTransactionalInput: {
            /** @enum {string} */
            provider: "sendgrid" | "mailchimp" | "klaviyo";
            /** Format: email */
            to: string;
            /** Format: email */
            from?: string;
            subject: string;
            template_id?: string;
            html?: string;
            text?: string;
            variables?: {
                [key: string]: string | number | boolean;
            };
        };
        /** @description Normalized send_transactional result. */
        SendTransactionalData: {
            provider: components["schemas"]["Provider"];
            /** @example msg_123 */
            message_id: string;
            /** @enum {string} */
            action: "sent";
        };
        /**
         * @description Fetch normalized campaign metrics.
         * @example {
         *       "provider": "sendgrid",
         *       "campaign_id": "campaign_123"
         *     }
         */
        GetCampaignStatsInput: {
            /** @enum {string} */
            provider: "sendgrid" | "mailchimp" | "klaviyo";
            campaign_id: string;
        };
        /** @description Normalized get_campaign_stats result. */
        CampaignStatsData: {
            provider: components["schemas"]["Provider"];
            /** @example campaign_123 */
            campaign_id: string;
            /** @example 1000 */
            sent: number;
            /** @example 420 */
            opens: number;
            /** @example 120 */
            clicks: number;
            /** @example 8 */
            bounces: number;
            /** @example 3 */
            unsubscribes: number;
            /**
             * @example {
             *       "start": "2026-04-01T00:00:00.000Z",
             *       "end": "2026-04-27T00:00:00.000Z"
             *     }
             */
            period: {
                /**
                 * Format: date-time
                 * @description ISO 8601 timestamp.
                 * @example 2026-04-27T12:00:00.000Z
                 */
                start: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 timestamp.
                 * @example 2026-04-27T12:00:00.000Z
                 */
                end: string;
            };
        };
        /**
         * @description List provider templates with normalized cursor pagination.
         * @example {
         *       "provider": "sendgrid",
         *       "limit": 25
         *     }
         */
        ListTemplatesInput: {
            /** @enum {string} */
            provider: "sendgrid" | "mailchimp" | "klaviyo";
            /** @default 25 */
            limit: number;
            cursor?: string;
        };
        /** @description Normalized list_templates result. */
        ListTemplatesData: {
            provider: components["schemas"]["Provider"];
            templates: {
                /** @example tmpl_123 */
                id: string;
                /** @example Welcome email */
                name: string;
                /** @example null */
                subject: string | null;
                /**
                 * Format: date-time
                 * @description ISO 8601 timestamp.
                 * @example 2026-04-27T12:00:00.000Z
                 */
                updated_at: string;
            }[];
            /** @example null */
            next_cursor: string | null;
        };
        /**
         * @description List provider campaigns with normalized status and cursor pagination.
         * @example {
         *       "provider": "sendgrid",
         *       "status": "all",
         *       "limit": 25
         *     }
         */
        ListCampaignsInput: {
            /** @enum {string} */
            provider: "sendgrid" | "mailchimp" | "klaviyo";
            /**
             * @default all
             * @enum {string}
             */
            status: "draft" | "scheduled" | "sent" | "all";
            /** @default 25 */
            limit: number;
            cursor?: string;
        };
        /** @description Normalized list_campaigns result. */
        ListCampaignsData: {
            provider: components["schemas"]["Provider"];
            campaigns: {
                /** @example camp_123 */
                id: string;
                /** @example Spring promo */
                name: string;
                /**
                 * @example sent
                 * @enum {string}
                 */
                status: "draft" | "scheduled" | "sent" | "unknown";
                /**
                 * Format: date-time
                 * @description ISO 8601 timestamp.
                 * @example 2026-04-27T12:00:00.000Z
                 */
                updated_at: string;
            }[];
            /** @example null */
            next_cursor: string | null;
        };
        /**
         * @description Create a Vorlek account and initial live/test API keys.
         * @example {
         *       "email": "operator@example.com",
         *       "password": "correct horse battery staple"
         *     }
         */
        SignupInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @description Account signup result. API keys are displayed once. */
        SignupResponse: {
            /** Format: uuid */
            account_id: string;
            /** Format: email */
            email: string;
            /** @example vk_live_xxxxxxxxxxxxxxxxxxxxxxxx */
            live_api_key: string;
            /** @example vk_test_xxxxxxxxxxxxxxxxxxxxxxxx */
            test_api_key: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp.
             * @example 2026-04-27T12:00:00.000Z
             */
            created_at: string;
            warning: string;
        };
        /** @description Rotated API key response. */
        RotateApiKeyResponse: {
            /** Format: uuid */
            api_key_id: string;
            /** @example vk_live_xxxxxxxxxxxxxxxxxxxxxxxx */
            api_key: string;
            /** @enum {string} */
            mode: "live" | "test";
            warning: string;
        };
        /** @description Authenticated account identity. */
        Account: {
            /** Format: uuid */
            account_id: string;
            /** Format: email */
            email: string;
            /** @example free */
            plan: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp.
             * @example 2026-04-27T12:00:00.000Z
             */
            created_at: string;
        };
        /** @description Current account usage summary. */
        AccountUsage: {
            period: {
                /**
                 * Format: date-time
                 * @description ISO 8601 timestamp.
                 * @example 2026-04-27T12:00:00.000Z
                 */
                start: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 timestamp.
                 * @example 2026-04-27T12:00:00.000Z
                 */
                end: string;
            };
            quota: components["schemas"]["QuotaMeta"];
            recent_operations: {
                total: number;
                errors: number;
                by_tool: {
                    [key: string]: number;
                };
            };
        };
        /**
         * @description Connect and validate provider credentials.
         * @example {
         *       "provider": "sendgrid",
         *       "api_key": "SG.x"
         *     }
         */
        CreateConnectionInput: {
            /** @enum {string} */
            provider: "sendgrid";
            api_key: string;
        } | {
            /** @enum {string} */
            provider: "mailchimp";
            api_key: string;
            list_id?: string;
        } | {
            /** @enum {string} */
            provider: "klaviyo";
            api_key: string;
        };
        /** @description Provider connection summary. */
        Connection: {
            /** Format: uuid */
            connection_id: string;
            provider: components["schemas"]["Provider"];
            /** @example active */
            status: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp.
             * @example 2026-04-27T12:00:00.000Z
             */
            last_validated_at?: string | null;
            account_name?: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp.
             * @example 2026-04-27T12:00:00.000Z
             */
            created_at?: string;
        };
        DeleteConnectionResponse: {
            provider: components["schemas"]["Provider"];
            /** @enum {boolean} */
            deleted: true;
        };
        SkillVersion: {
            /** @enum {string} */
            name: "vorlek";
            /** @example 0.3.0 */
            version: string;
            /**
             * Format: uri
             * @example https://vorlek.dev/skill.md
             */
            skill_md_url: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            service: "vorlek-api";
            version: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp.
             * @example 2026-04-27T12:00:00.000Z
             */
            timestamp: string;
            checks: {
                /** @enum {string} */
                db: "ok" | "down";
                /** @enum {string} */
                redis: "ok" | "down";
            };
        };
        /** @description UpsertContactResponse response envelope. */
        UpsertContactResponse: {
            /** @enum {string} */
            status: "success";
            data: components["schemas"]["UpsertContactData"];
            meta: components["schemas"]["SuccessMeta"];
            tip: string | null;
        };
        /** @description GetConnectionStatusResponse response envelope. */
        GetConnectionStatusResponse: {
            /** @enum {string} */
            status: "success";
            data: components["schemas"]["ConnectionStatusData"];
            meta: components["schemas"]["SuccessMeta"];
            tip: string | null;
        };
        /** @description SendTransactionalResponse response envelope. */
        SendTransactionalResponse: {
            /** @enum {string} */
            status: "success";
            data: components["schemas"]["SendTransactionalData"];
            meta: components["schemas"]["SuccessMeta"];
            tip: string | null;
        };
        /** @description GetCampaignStatsResponse response envelope. */
        GetCampaignStatsResponse: {
            /** @enum {string} */
            status: "success";
            data: components["schemas"]["CampaignStatsData"];
            meta: components["schemas"]["SuccessMeta"];
            tip: string | null;
        };
        /** @description ListTemplatesResponse response envelope. */
        ListTemplatesResponse: {
            /** @enum {string} */
            status: "success";
            data: components["schemas"]["ListTemplatesData"];
            meta: components["schemas"]["SuccessMeta"];
            tip: string | null;
        };
        /** @description ListCampaignsResponse response envelope. */
        ListCampaignsResponse: {
            /** @enum {string} */
            status: "success";
            data: components["schemas"]["ListCampaignsData"];
            meta: components["schemas"]["SuccessMeta"];
            tip: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
